#!/usr/bin/env python3
import sys
import requests
import threading
import time

start = time.time()

urls = sys.stdin.readlines()
idx = 1

def write_url(url, index):
    r = requests.get(url)
    f = open(str(index) + ".html", "w")

    if r.status_code == 200:
        f.write(r.text)
    else:
        f.write("FAILED")
    f.close()


threads = []
for url in urls:
    url = url.strip()

    t = threading.Thread(target=write_url, args=(url, idx))
    threads.append(t)
    t.start()
    idx += 1

for t in threads:
    t.join()


# for url in urls:
#     url = url.strip()
#
#     write_url(url, idx)
#     idx += 1


print("Time taken: ", time.time() - start)